/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.diego.aulainterfacevisual;

/**
 *
 * @author ct67ca
 */
public class Form1 extends javax.swing.JFrame {

    /**
     * Creates new form Form1
     */
    public Form1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main = new javax.swing.JPanel();
        gameTitle = new javax.swing.JLabel();
        linha01 = new javax.swing.JPanel();
        linha1Campo1 = new javax.swing.JTextField();
        linha1Campo2 = new javax.swing.JTextField();
        linha1Campo3 = new javax.swing.JTextField();
        linha1Campo6 = new javax.swing.JTextField();
        linha1Campo5 = new javax.swing.JTextField();
        linha1Campo4 = new javax.swing.JTextField();
        linha02 = new javax.swing.JPanel();
        linha2Campo1 = new javax.swing.JTextField();
        linha2Campo2 = new javax.swing.JTextField();
        linha2Campo3 = new javax.swing.JTextField();
        linha2Campo4 = new javax.swing.JTextField();
        linha2Campo5 = new javax.swing.JTextField();
        linha2Campo6 = new javax.swing.JTextField();
        linha03 = new javax.swing.JPanel();
        linha3Campo1 = new javax.swing.JTextField();
        linha3Campo2 = new javax.swing.JTextField();
        linha3Campo3 = new javax.swing.JTextField();
        linha3Campo4 = new javax.swing.JTextField();
        linha3Campo5 = new javax.swing.JTextField();
        linha3Campo6 = new javax.swing.JTextField();
        linha04 = new javax.swing.JPanel();
        linha4Campo1 = new javax.swing.JTextField();
        linha4Campo2 = new javax.swing.JTextField();
        linha4Campo3 = new javax.swing.JTextField();
        linha4Campo4 = new javax.swing.JTextField();
        linha4Campo5 = new javax.swing.JTextField();
        linha4Campo6 = new javax.swing.JTextField();
        ButtonJogar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        setFont(new java.awt.Font("72 Black", 0, 10)); // NOI18N
        setForeground(java.awt.Color.darkGray);
        setName("main"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        main.setBackground(new java.awt.Color(51, 51, 51));

        gameTitle.setFont(new java.awt.Font("Bosch Sans", 1, 36)); // NOI18N
        gameTitle.setForeground(new java.awt.Color(255, 255, 255));
        gameTitle.setText("TERMO DO CORINTHIANS");
        gameTitle.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        linha01.setBackground(new java.awt.Color(255, 255, 255));
        linha01.setOpaque(false);
        linha01.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                linha01PropertyChange(evt);
            }
        });

        linha1Campo1.setBackground(new java.awt.Color(153, 153, 153));
        linha1Campo1.setFont(new java.awt.Font("Bosch Sans", 1, 48)); // NOI18N
        linha1Campo1.setForeground(new java.awt.Color(255, 255, 255));
        linha1Campo1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        linha1Campo1.setName("linha1Campo1"); // NOI18N
        linha1Campo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linha1Campo1ActionPerformed(evt);
            }
        });
        linha1Campo1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                linha1Campo1PropertyChange(evt);
            }
        });

        linha1Campo2.setBackground(new java.awt.Color(153, 153, 153));
        linha1Campo2.setFont(new java.awt.Font("Bosch Sans", 1, 48)); // NOI18N
        linha1Campo2.setForeground(new java.awt.Color(255, 255, 255));
        linha1Campo2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        linha1Campo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linha1Campo2ActionPerformed(evt);
            }
        });

        linha1Campo3.setBackground(new java.awt.Color(153, 153, 153));
        linha1Campo3.setFont(new java.awt.Font("Bosch Sans", 1, 48)); // NOI18N
        linha1Campo3.setForeground(new java.awt.Color(255, 255, 255));
        linha1Campo3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        linha1Campo3.setName("linha1Campo1"); // NOI18N
        linha1Campo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linha1Campo3ActionPerformed(evt);
            }
        });

        linha1Campo6.setBackground(new java.awt.Color(153, 153, 153));
        linha1Campo6.setFont(new java.awt.Font("Bosch Sans", 1, 48)); // NOI18N
        linha1Campo6.setForeground(new java.awt.Color(255, 255, 255));
        linha1Campo6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        linha1Campo6.setName("linha1Campo1"); // NOI18N
        linha1Campo6.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                linha1Campo6InputMethodTextChanged(evt);
            }
        });
        linha1Campo6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linha1Campo6ActionPerformed(evt);
            }
        });
        linha1Campo6.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                linha1Campo6PropertyChange(evt);
            }
        });
        linha1Campo6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                linha1Campo6KeyPressed(evt);
            }
        });

        linha1Campo5.setBackground(new java.awt.Color(153, 153, 153));
        linha1Campo5.setFont(new java.awt.Font("Bosch Sans", 1, 48)); // NOI18N
        linha1Campo5.setForeground(new java.awt.Color(255, 255, 255));
        linha1Campo5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        linha1Campo5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linha1Campo5ActionPerformed(evt);
            }
        });

        linha1Campo4.setBackground(new java.awt.Color(153, 153, 153));
        linha1Campo4.setFont(new java.awt.Font("Bosch Sans", 1, 48)); // NOI18N
        linha1Campo4.setForeground(new java.awt.Color(255, 255, 255));
        linha1Campo4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        linha1Campo4.setName("linha1Campo1"); // NOI18N
        linha1Campo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linha1Campo4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout linha01Layout = new javax.swing.GroupLayout(linha01);
        linha01.setLayout(linha01Layout);
        linha01Layout.setHorizontalGroup(
            linha01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(linha01Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(linha1Campo1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(linha1Campo2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(linha1Campo3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(linha1Campo4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(linha1Campo5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(linha1Campo6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        linha01Layout.setVerticalGroup(
            linha01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, linha01Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(linha01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(linha1Campo3)
                    .addComponent(linha1Campo1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(linha1Campo6)
                    .addComponent(linha1Campo4, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, linha01Layout.createSequentialGroup()
                        .addGroup(linha01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(linha1Campo2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(linha1Campo5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        linha02.setBorder(javax.swing.BorderFactory.createBevelBorder(0, java.awt.Color.lightGray, java.awt.Color.lightGray, null, null));
        linha02.setOpaque(false);
        linha02.setPreferredSize(new java.awt.Dimension(646, 101));

        linha2Campo1.setBackground(new java.awt.Color(153, 153, 153));
        linha2Campo1.setFont(new java.awt.Font("Bosch Sans", 1, 48)); // NOI18N
        linha2Campo1.setForeground(new java.awt.Color(255, 255, 255));
        linha2Campo1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        linha2Campo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linha2Campo1ActionPerformed(evt);
            }
        });

        linha2Campo2.setBackground(new java.awt.Color(153, 153, 153));
        linha2Campo2.setFont(new java.awt.Font("Bosch Sans", 1, 48)); // NOI18N
        linha2Campo2.setForeground(new java.awt.Color(255, 255, 255));
        linha2Campo2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        linha2Campo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linha2Campo2ActionPerformed(evt);
            }
        });

        linha2Campo3.setBackground(new java.awt.Color(153, 153, 153));
        linha2Campo3.setFont(new java.awt.Font("Bosch Sans", 1, 48)); // NOI18N
        linha2Campo3.setForeground(new java.awt.Color(255, 255, 255));
        linha2Campo3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        linha2Campo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linha2Campo3ActionPerformed(evt);
            }
        });

        linha2Campo4.setBackground(new java.awt.Color(153, 153, 153));
        linha2Campo4.setFont(new java.awt.Font("Bosch Sans", 1, 48)); // NOI18N
        linha2Campo4.setForeground(new java.awt.Color(255, 255, 255));
        linha2Campo4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        linha2Campo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linha2Campo4ActionPerformed(evt);
            }
        });

        linha2Campo5.setBackground(new java.awt.Color(153, 153, 153));
        linha2Campo5.setFont(new java.awt.Font("Bosch Sans", 1, 48)); // NOI18N
        linha2Campo5.setForeground(new java.awt.Color(255, 255, 255));
        linha2Campo5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        linha2Campo5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linha2Campo5ActionPerformed(evt);
            }
        });

        linha2Campo6.setBackground(new java.awt.Color(153, 153, 153));
        linha2Campo6.setFont(new java.awt.Font("Bosch Sans", 1, 48)); // NOI18N
        linha2Campo6.setForeground(new java.awt.Color(255, 255, 255));
        linha2Campo6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        linha2Campo6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linha2Campo6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout linha02Layout = new javax.swing.GroupLayout(linha02);
        linha02.setLayout(linha02Layout);
        linha02Layout.setHorizontalGroup(
            linha02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(linha02Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(linha2Campo1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(linha2Campo2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(linha2Campo3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(linha2Campo4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(linha2Campo5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(linha2Campo6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        linha02Layout.setVerticalGroup(
            linha02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, linha02Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(linha02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(linha2Campo1, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                    .addComponent(linha2Campo2)
                    .addComponent(linha2Campo3)
                    .addComponent(linha2Campo4)
                    .addComponent(linha2Campo5)
                    .addComponent(linha2Campo6, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );

        linha03.setBorder(javax.swing.BorderFactory.createBevelBorder(0, java.awt.Color.lightGray, java.awt.Color.lightGray, null, null));
        linha03.setOpaque(false);
        linha03.setPreferredSize(new java.awt.Dimension(646, 101));

        linha3Campo1.setBackground(new java.awt.Color(153, 153, 153));
        linha3Campo1.setFont(new java.awt.Font("Bosch Sans", 1, 48)); // NOI18N
        linha3Campo1.setForeground(new java.awt.Color(255, 255, 255));
        linha3Campo1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        linha3Campo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linha3Campo1ActionPerformed(evt);
            }
        });

        linha3Campo2.setBackground(new java.awt.Color(153, 153, 153));
        linha3Campo2.setFont(new java.awt.Font("Bosch Sans", 1, 48)); // NOI18N
        linha3Campo2.setForeground(new java.awt.Color(255, 255, 255));
        linha3Campo2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        linha3Campo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linha3Campo2ActionPerformed(evt);
            }
        });

        linha3Campo3.setBackground(new java.awt.Color(153, 153, 153));
        linha3Campo3.setFont(new java.awt.Font("Bosch Sans", 1, 48)); // NOI18N
        linha3Campo3.setForeground(new java.awt.Color(255, 255, 255));
        linha3Campo3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        linha3Campo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linha3Campo3ActionPerformed(evt);
            }
        });

        linha3Campo4.setBackground(new java.awt.Color(153, 153, 153));
        linha3Campo4.setFont(new java.awt.Font("Bosch Sans", 1, 48)); // NOI18N
        linha3Campo4.setForeground(new java.awt.Color(255, 255, 255));
        linha3Campo4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        linha3Campo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linha3Campo4ActionPerformed(evt);
            }
        });

        linha3Campo5.setBackground(new java.awt.Color(153, 153, 153));
        linha3Campo5.setFont(new java.awt.Font("Bosch Sans", 1, 48)); // NOI18N
        linha3Campo5.setForeground(new java.awt.Color(255, 255, 255));
        linha3Campo5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        linha3Campo5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linha3Campo5ActionPerformed(evt);
            }
        });

        linha3Campo6.setBackground(new java.awt.Color(153, 153, 153));
        linha3Campo6.setFont(new java.awt.Font("Bosch Sans", 1, 48)); // NOI18N
        linha3Campo6.setForeground(new java.awt.Color(255, 255, 255));
        linha3Campo6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        linha3Campo6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linha3Campo6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout linha03Layout = new javax.swing.GroupLayout(linha03);
        linha03.setLayout(linha03Layout);
        linha03Layout.setHorizontalGroup(
            linha03Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(linha03Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(linha3Campo1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(linha3Campo2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(linha3Campo3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(linha3Campo4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(linha3Campo5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(linha3Campo6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        linha03Layout.setVerticalGroup(
            linha03Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, linha03Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(linha03Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(linha3Campo1, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                    .addComponent(linha3Campo2)
                    .addComponent(linha3Campo3)
                    .addComponent(linha3Campo4)
                    .addComponent(linha3Campo5)
                    .addComponent(linha3Campo6, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );

        linha04.setBorder(javax.swing.BorderFactory.createBevelBorder(0, java.awt.Color.lightGray, java.awt.Color.lightGray, null, null));
        linha04.setOpaque(false);
        linha04.setPreferredSize(new java.awt.Dimension(646, 101));

        linha4Campo1.setBackground(new java.awt.Color(153, 153, 153));
        linha4Campo1.setFont(new java.awt.Font("Bosch Sans", 1, 48)); // NOI18N
        linha4Campo1.setForeground(new java.awt.Color(255, 255, 255));
        linha4Campo1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        linha4Campo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linha4Campo1ActionPerformed(evt);
            }
        });

        linha4Campo2.setBackground(new java.awt.Color(153, 153, 153));
        linha4Campo2.setFont(new java.awt.Font("Bosch Sans", 1, 48)); // NOI18N
        linha4Campo2.setForeground(new java.awt.Color(255, 255, 255));
        linha4Campo2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        linha4Campo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linha4Campo2ActionPerformed(evt);
            }
        });

        linha4Campo3.setBackground(new java.awt.Color(153, 153, 153));
        linha4Campo3.setFont(new java.awt.Font("Bosch Sans", 1, 48)); // NOI18N
        linha4Campo3.setForeground(new java.awt.Color(255, 255, 255));
        linha4Campo3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        linha4Campo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linha4Campo3ActionPerformed(evt);
            }
        });

        linha4Campo4.setBackground(new java.awt.Color(153, 153, 153));
        linha4Campo4.setFont(new java.awt.Font("Bosch Sans", 1, 48)); // NOI18N
        linha4Campo4.setForeground(new java.awt.Color(255, 255, 255));
        linha4Campo4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        linha4Campo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linha4Campo4ActionPerformed(evt);
            }
        });

        linha4Campo5.setBackground(new java.awt.Color(153, 153, 153));
        linha4Campo5.setFont(new java.awt.Font("Bosch Sans", 1, 48)); // NOI18N
        linha4Campo5.setForeground(new java.awt.Color(255, 255, 255));
        linha4Campo5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        linha4Campo5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linha4Campo5ActionPerformed(evt);
            }
        });

        linha4Campo6.setBackground(new java.awt.Color(153, 153, 153));
        linha4Campo6.setFont(new java.awt.Font("Bosch Sans", 1, 48)); // NOI18N
        linha4Campo6.setForeground(new java.awt.Color(255, 255, 255));
        linha4Campo6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        linha4Campo6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linha4Campo6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout linha04Layout = new javax.swing.GroupLayout(linha04);
        linha04.setLayout(linha04Layout);
        linha04Layout.setHorizontalGroup(
            linha04Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(linha04Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(linha4Campo1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(linha4Campo2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(linha4Campo3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(linha4Campo4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(linha4Campo5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(linha4Campo6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        linha04Layout.setVerticalGroup(
            linha04Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, linha04Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(linha04Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(linha4Campo1, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                    .addComponent(linha4Campo2)
                    .addComponent(linha4Campo3)
                    .addComponent(linha4Campo4)
                    .addComponent(linha4Campo5)
                    .addComponent(linha4Campo6, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );

        ButtonJogar.setBackground(new java.awt.Color(0, 204, 0));
        ButtonJogar.setFont(new java.awt.Font("Bosch Sans", 1, 14)); // NOI18N
        ButtonJogar.setText("JOGAR");
        ButtonJogar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonJogarMouseClicked(evt);
            }
        });
        ButtonJogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonJogarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainLayout = new javax.swing.GroupLayout(main);
        main.setLayout(mainLayout);
        mainLayout.setHorizontalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainLayout.createSequentialGroup()
                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainLayout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(linha01, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(linha02, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(linha03, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(linha04, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(mainLayout.createSequentialGroup()
                        .addGap(311, 311, 311)
                        .addComponent(gameTitle)
                        .addGap(98, 98, 98)
                        .addComponent(ButtonJogar, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(140, Short.MAX_VALUE))
        );
        mainLayout.setVerticalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainLayout.createSequentialGroup()
                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(gameTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(ButtonJogar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(linha01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(linha02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(linha03, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(linha04, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void linha1Campo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linha1Campo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_linha1Campo1ActionPerformed

    private void linha1Campo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linha1Campo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_linha1Campo2ActionPerformed

    private void linha1Campo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linha1Campo3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_linha1Campo3ActionPerformed

    private void linha1Campo6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linha1Campo6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_linha1Campo6ActionPerformed

    private void linha1Campo5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linha1Campo5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_linha1Campo5ActionPerformed

    private void linha1Campo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linha1Campo4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_linha1Campo4ActionPerformed

    private void linha2Campo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linha2Campo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_linha2Campo1ActionPerformed

    private void linha2Campo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linha2Campo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_linha2Campo2ActionPerformed

    private void linha2Campo5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linha2Campo5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_linha2Campo5ActionPerformed

    private void linha2Campo6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linha2Campo6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_linha2Campo6ActionPerformed

    private void linha3Campo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linha3Campo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_linha3Campo1ActionPerformed

    private void linha3Campo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linha3Campo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_linha3Campo2ActionPerformed

    private void linha3Campo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linha3Campo3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_linha3Campo3ActionPerformed

    private void linha3Campo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linha3Campo4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_linha3Campo4ActionPerformed

    private void linha3Campo5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linha3Campo5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_linha3Campo5ActionPerformed

    private void linha3Campo6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linha3Campo6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_linha3Campo6ActionPerformed

    private void linha4Campo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linha4Campo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_linha4Campo1ActionPerformed

    private void linha4Campo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linha4Campo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_linha4Campo2ActionPerformed

    private void linha4Campo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linha4Campo3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_linha4Campo3ActionPerformed

    private void linha4Campo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linha4Campo4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_linha4Campo4ActionPerformed

    private void linha4Campo5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linha4Campo5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_linha4Campo5ActionPerformed

    private void linha4Campo6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linha4Campo6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_linha4Campo6ActionPerformed

    private void linha2Campo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linha2Campo3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_linha2Campo3ActionPerformed

    private void linha2Campo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linha2Campo4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_linha2Campo4ActionPerformed

    private void ButtonJogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonJogarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonJogarActionPerformed

    private void linha1Campo1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_linha1Campo1PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_linha1Campo1PropertyChange

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        evt.setSource(EXIT_ON_CLOSE);        // TODO add your handling code here:;
    }//GEN-LAST:event_formWindowClosed

    private void ButtonJogarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonJogarMouseClicked
        System.out.println("Jogar");        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonJogarMouseClicked

    private void linha01PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_linha01PropertyChange
       // TODO add your handling code here:
    }//GEN-LAST:event_linha01PropertyChange

    private void linha1Campo6PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_linha1Campo6PropertyChange
       // TODO add your handling code here:
    }//GEN-LAST:event_linha1Campo6PropertyChange

    private void linha1Campo6InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_linha1Campo6InputMethodTextChanged
       // TODO add your handling code here:
    }//GEN-LAST:event_linha1Campo6InputMethodTextChanged

    private void linha1Campo6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_linha1Campo6KeyPressed
        System.out.println("clicaram " + evt.getKeyChar());        // TODO add your handling code here:
    }//GEN-LAST:event_linha1Campo6KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonJogar;
    private javax.swing.JLabel gameTitle;
    private javax.swing.JPanel linha01;
    private javax.swing.JPanel linha02;
    private javax.swing.JPanel linha03;
    private javax.swing.JPanel linha04;
    private javax.swing.JTextField linha1Campo1;
    private javax.swing.JTextField linha1Campo2;
    private javax.swing.JTextField linha1Campo3;
    private javax.swing.JTextField linha1Campo4;
    private javax.swing.JTextField linha1Campo5;
    private javax.swing.JTextField linha1Campo6;
    private javax.swing.JTextField linha2Campo1;
    private javax.swing.JTextField linha2Campo2;
    private javax.swing.JTextField linha2Campo3;
    private javax.swing.JTextField linha2Campo4;
    private javax.swing.JTextField linha2Campo5;
    private javax.swing.JTextField linha2Campo6;
    private javax.swing.JTextField linha3Campo1;
    private javax.swing.JTextField linha3Campo2;
    private javax.swing.JTextField linha3Campo3;
    private javax.swing.JTextField linha3Campo4;
    private javax.swing.JTextField linha3Campo5;
    private javax.swing.JTextField linha3Campo6;
    private javax.swing.JTextField linha4Campo1;
    private javax.swing.JTextField linha4Campo2;
    private javax.swing.JTextField linha4Campo3;
    private javax.swing.JTextField linha4Campo4;
    private javax.swing.JTextField linha4Campo5;
    private javax.swing.JTextField linha4Campo6;
    private javax.swing.JPanel main;
    // End of variables declaration//GEN-END:variables
}
